# **ÖDEV-2**

1-Numpy kütüphanesini import edin.

In [1]:
import numpy as np

2-1'den 5 e kadar (5 dahil) b isimli bir dizi oluşturun.

In [3]:
b = np.arange(1,6,1)
print(b)

[1 2 3 4 5]


3- 20 adet 0'dan oluşan 4 x 5' lik dizi oluşturun.

In [4]:
zerosMatrix = np.zeros((4,5), dtype = int)
print(zerosMatrix)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


4- 15 adet 7 sayısından oluşan diziyi 3x5 olarak yazın.

In [6]:
sevensMatrix = np.full((3,5), 7)
print(sevensMatrix)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


5- 10–70 e kadar 5 er artan sayıları yaz.

In [7]:
np.arange(10,71, 5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70])

6- 10–20 arasında 15 aynı uzaklıkta elemanı olan array oluşturun. (linspace metodunu kullanın.)

In [8]:
np.linspace(10,20,15)

array([10.        , 10.71428571, 11.42857143, 12.14285714, 12.85714286,
       13.57142857, 14.28571429, 15.        , 15.71428571, 16.42857143,
       17.14285714, 17.85714286, 18.57142857, 19.28571429, 20.        ])

7- Rastgele sayılardan oluşan diziyi 3x5 boyutunda yazdır.

In [13]:
np.random.randint(10, size=(3,5))

array([[5, 2, 6, 0, 5],
       [2, 3, 1, 5, 4],
       [8, 1, 8, 7, 9]])

8- 5 elemanlı birim matris oluşturun. eye() metodu kullanın.

In [14]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

9- 0'dan 24 e kadar array oluştur. Sonra reshape metodu ile 4x6 boyutu olarak yazın.

In [19]:
a = np.arange(0,24).reshape((4,6))
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


10- 0 ile 1 arasında rastgele 10 sayıdan oluşan bir array tanımlayın. Minimum ve maksimum değerleri bulun.

In [23]:
sortedArr = np.random.random(10)
print(sortedArr)

print("Minimum vale of array is: " + str(min(sortedArr)))
print("maximum vale of array is: " + str(max(sortedArr)))

[0.77493118 0.55493738 0.2496477  0.02890989 0.08192697 0.73130031
 0.8648203  0.24198961 0.56645591 0.01877122]
Minimum vale of array is: 0.01877122221730121
maximum vale of array is: 0.8648203046757139


11- 36 sayıdan oluşan rastgele sayılar 6x6' lık array olarak yazdırın.

In [26]:
newArr = np.random.randint(100, size=(6,6))
print(newArr)

[[44 33 86 28 58  6]
 [90 75 67 12 57 55]
 [58 67 70 83 72 15]
 [74 53 79 20 22 52]
 [35 98 24 78 97 27]
 [73 80 72 70 50  2]]


12- 5.satırdaki elemanları gösteriniz.

In [57]:
print(newArr[4,:])

[35 98 24 78 97 27]


13- 6.satır ve 6.sutundaki elemanları gösteriniz.

In [44]:
print("6. row: " + str(newArr[5,:]))
print("6. column: " + str(newArr[:,5]))

6. row: [73 80 72 70 50  2]
6. column: [ 6 55 15 52 27  2]


14-4.sutundaki tüm elemanları çekin.

In [58]:
print("4. column: " + str(newArr[:,3]))

4. column: [28 12 83 20 78 70]


15- For döngüsünü ve flat metodunu kullanarak satır satır elemanları yazdırınız.

In [72]:
for i in range(len(newArr)):
    print(newArr[i,:].flatten())

[44 33 86 28 58  6]
[90 75 67 12 57 55]
[58 67 70 83 72 15]
[74 53 79 20 22 52]
[35 98 24 78 97 27]
[73 80 72 70 50  2]


16- 0 ile 1 aralığında bir array oluştur. Bu array değerini 5 ile çarpın.

In [93]:
randomArr =  np.random.random((5,5))
print(randomArr)

print("\n" + str(np.multiply(randomArr,5)))

[[0.66990748 0.87891365 0.55664246 0.31464497 0.91919487]
 [0.33249542 0.72875928 0.17348528 0.27206564 0.65296921]
 [0.00139572 0.82296984 0.86499232 0.72410964 0.036304  ]
 [0.01340055 0.35952031 0.1070014  0.7753943  0.50118954]
 [0.733375   0.25325408 0.19414856 0.81399643 0.04557789]]

[[3.34953738 4.39456823 2.7832123  1.57322485 4.59597435]
 [1.66247708 3.64379638 0.86742642 1.36032821 3.26484607]
 [0.00697858 4.11484921 4.32496158 3.62054822 0.18151998]
 [0.06700273 1.79760156 0.53500699 3.8769715  2.50594771]
 [3.66687502 1.26627042 0.97074279 4.06998213 0.22788943]]


16- Satırların toplam değeri nedir?

In [108]:
for i in range(len(randomArr)):
    print("Sum of " + str(i+1) + ". row: " + str(sum(randomArr[i,:])))

Sum of 1. row: 3.3393034228827654
Sum of 2. row: 2.1597748324596058
Sum of 3. row: 2.4497715127683843
Sum of 4. row: 1.7565060975188773
Sum of 5. row: 2.040351957760277


17-Satırların standart sapma değeri nedir?

In [111]:
for i in range(len(randomArr)):
    print("standard deviation of " + str(i+1) + ". row: " + str(np.std(randomArr[i,:])))

standard deviation of 1. row: 0.22129041980772698
standard deviation of 2. row: 0.2187251563377594
standard deviation of 3. row: 0.38752281936287536
standard deviation of 4. row: 0.27431670448848094
standard deviation of 5. row: 0.30715810032966256


18-Satırların varyans değeri nedir?

In [112]:
for i in range(len(randomArr)):
    print("Variance of " + str(i+1) + ". row: " + str(np.var(randomArr[i,:])))

Variance of 1. row: 0.04896944989868005
Variance of 2. row: 0.0478406940149773
Variance of 3. row: 0.1501739355269517
Variance of 4. row: 0.07524965436142059
Variance of 5. row: 0.09434609859812705


19- Satırların transpoz değeri nedir?

In [113]:
print(randomArr.T)

[[0.66990748 0.33249542 0.00139572 0.01340055 0.733375  ]
 [0.87891365 0.72875928 0.82296984 0.35952031 0.25325408]
 [0.55664246 0.17348528 0.86499232 0.1070014  0.19414856]
 [0.31464497 0.27206564 0.72410964 0.7753943  0.81399643]
 [0.91919487 0.65296921 0.036304   0.50118954 0.04557789]]
